
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.saudade.vortex.init;

import net.saudade.vortex.item.WillOfTheChaosbornItem;
import net.saudade.vortex.item.WhisperOfTheAlluringAbyssItem;
import net.saudade.vortex.item.WhirlOfExistenceItem;
import net.saudade.vortex.item.WheatIconItem;
import net.saudade.vortex.item.WeakRunestoneItem;
import net.saudade.vortex.item.WarriorsContractItem;
import net.saudade.vortex.item.VisageOfDepartedRulersItem;
import net.saudade.vortex.item.UltimateRunestoneItem;
import net.saudade.vortex.item.TravelersDiaryItem;
import net.saudade.vortex.item.TravelersContractItem;
import net.saudade.vortex.item.ThePlagueIngotItem;
import net.saudade.vortex.item.ThePearlOfGnumusesItem;
import net.saudade.vortex.item.TheEssenceOfADemiGodItem;
import net.saudade.vortex.item.TheCursedHandItem;
import net.saudade.vortex.item.TearOfTheAllfathersItem;
import net.saudade.vortex.item.TabletOfTremblingOfEarthItem;
import net.saudade.vortex.item.TabletOfSwingingMapleItem;
import net.saudade.vortex.item.TabletOfStormItem;
import net.saudade.vortex.item.TabletOfLostHousesItem;
import net.saudade.vortex.item.TabletOfFarThunderItem;
import net.saudade.vortex.item.TabletOfFallenDestiniesItem;
import net.saudade.vortex.item.TabletOfClearSkyItem;
import net.saudade.vortex.item.TabletOfCataclysmItem;
import net.saudade.vortex.item.TabletOfBreathOfWindItem;
import net.saudade.vortex.item.TabletOfAbandonedPlacesItem;
import net.saudade.vortex.item.SwordandShieldIconItem;
import net.saudade.vortex.item.StrongRunestoneItem;
import net.saudade.vortex.item.StarIconItem;
import net.saudade.vortex.item.ScrollOfStrengthItem;
import net.saudade.vortex.item.ScrollIconItem;
import net.saudade.vortex.item.RoughStonyMixItem;
import net.saudade.vortex.item.RiftOfForgottenChaosItem;
import net.saudade.vortex.item.ResonatingCrystalHeartItem;
import net.saudade.vortex.item.RawRatTokenItem;
import net.saudade.vortex.item.RawGeminiumItem;
import net.saudade.vortex.item.RawChargedQualadiumItem;
import net.saudade.vortex.item.PowerfulRunestoneItem;
import net.saudade.vortex.item.PowerOfTheButterflyItem;
import net.saudade.vortex.item.PotionIconItem;
import net.saudade.vortex.item.PeeledFarmersSunflowerSeedItem;
import net.saudade.vortex.item.OzglozMixtureItem;
import net.saudade.vortex.item.OzglozIngotItem;
import net.saudade.vortex.item.OrcishSkullItem;
import net.saudade.vortex.item.OrcishQuiverItem;
import net.saudade.vortex.item.OrcishMonocleItem;
import net.saudade.vortex.item.OrcishDustItem;
import net.saudade.vortex.item.OrcishBottleItem;
import net.saudade.vortex.item.OrcishArtifactItem;
import net.saudade.vortex.item.NestIconItem;
import net.saudade.vortex.item.MysticalCoinItem;
import net.saudade.vortex.item.MysteriousManuscriptItem;
import net.saudade.vortex.item.MayoItem;
import net.saudade.vortex.item.MaterialEssenceItem;
import net.saudade.vortex.item.LightBlueScrollIconItem;
import net.saudade.vortex.item.LegendaryRunestoneItem;
import net.saudade.vortex.item.InsaneRunestoneItem;
import net.saudade.vortex.item.InnovatorsContractItem;
import net.saudade.vortex.item.IngotOfSproutedSteelItem;
import net.saudade.vortex.item.InfoIconItem;
import net.saudade.vortex.item.HumOfUnderwaterDepthsItem;
import net.saudade.vortex.item.HowlOfMercilessFlameItem;
import net.saudade.vortex.item.HomeIconItem;
import net.saudade.vortex.item.HexagonalManaStoneItem;
import net.saudade.vortex.item.HeatOfTheScorchingDesertItem;
import net.saudade.vortex.item.GreatRunestoneItem;
import net.saudade.vortex.item.GhostlyShardItem;
import net.saudade.vortex.item.GearIconItem;
import net.saudade.vortex.item.FriedFarmersSunflowerSeedItem;
import net.saudade.vortex.item.FarmersSunflowerHeadItem;
import net.saudade.vortex.item.FarmersContractItem;
import net.saudade.vortex.item.EssenceOfTheStormItem;
import net.saudade.vortex.item.EssenceOfNatureItem;
import net.saudade.vortex.item.EssenceOfMeltingItem;
import net.saudade.vortex.item.EssenceOfMagicItem;
import net.saudade.vortex.item.EssenceOfEarthquakeItem;
import net.saudade.vortex.item.EssenceOfCataclysmItem;
import net.saudade.vortex.item.EnchantersContractItem;
import net.saudade.vortex.item.DyingBreathOfForgottenTimesItem;
import net.saudade.vortex.item.DwarvenGearItem;
import net.saudade.vortex.item.DivineRunestoneItem;
import net.saudade.vortex.item.DefamedCrystalOutgrowthItem;
import net.saudade.vortex.item.CoreOfMatterItem;
import net.saudade.vortex.item.CommonRunestoneItem;
import net.saudade.vortex.item.CodexOfTruthItem;
import net.saudade.vortex.item.ClankOfTemperedMetalsItem;
import net.saudade.vortex.item.ClamorOfDeathsEmissariesItem;
import net.saudade.vortex.item.CartographersNotesItem;
import net.saudade.vortex.item.CackleOfVexingBlightItem;
import net.saudade.vortex.item.BrineItem;
import net.saudade.vortex.item.BreezeIconItem;
import net.saudade.vortex.item.BoxIconItem;
import net.saudade.vortex.item.BottleWithOilItem;
import net.saudade.vortex.item.BookIconItem;
import net.saudade.vortex.item.Book3IconItem;
import net.saudade.vortex.item.Book2IconItem;
import net.saudade.vortex.item.BloomingSteelIngotItem;
import net.saudade.vortex.item.AtomicSuspensionItem;
import net.saudade.vortex.item.AncientWritingsItem;
import net.saudade.vortex.item.AgilityoftheLynxItem;
import net.saudade.vortex.item.AdvancedRunestoneItem;
import net.saudade.vortex.block.display.CrankDisplayItem;
import net.saudade.vortex.VortexMod;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;

public class VortexModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, VortexMod.MODID);
	public static final RegistryObject<Item> FARMERS_SUNFLOWER = block(VortexModBlocks.FARMERS_SUNFLOWER);
	public static final RegistryObject<Item> BOX_ICON = REGISTRY.register("box_icon", () -> new BoxIconItem());
	public static final RegistryObject<Item> BREEZE_ICON = REGISTRY.register("breeze_icon", () -> new BreezeIconItem());
	public static final RegistryObject<Item> GEAR_ICON = REGISTRY.register("gear_icon", () -> new GearIconItem());
	public static final RegistryObject<Item> HOME_ICON = REGISTRY.register("home_icon", () -> new HomeIconItem());
	public static final RegistryObject<Item> INFO_ICON = REGISTRY.register("info_icon", () -> new InfoIconItem());
	public static final RegistryObject<Item> POTION_ICON = REGISTRY.register("potion_icon", () -> new PotionIconItem());
	public static final RegistryObject<Item> STAR_ICON = REGISTRY.register("star_icon", () -> new StarIconItem());
	public static final RegistryObject<Item> SWORDAND_SHIELD_ICON = REGISTRY.register("swordand_shield_icon", () -> new SwordandShieldIconItem());
	public static final RegistryObject<Item> WHEAT_ICON = REGISTRY.register("wheat_icon", () -> new WheatIconItem());
	public static final RegistryObject<Item> WEAK_RUNESTONE = REGISTRY.register("weak_runestone", () -> new WeakRunestoneItem());
	public static final RegistryObject<Item> COMMON_RUNESTONE = REGISTRY.register("common_runestone", () -> new CommonRunestoneItem());
	public static final RegistryObject<Item> STRONG_RUNESTONE = REGISTRY.register("strong_runestone", () -> new StrongRunestoneItem());
	public static final RegistryObject<Item> ADVANCED_RUNESTONE = REGISTRY.register("advanced_runestone", () -> new AdvancedRunestoneItem());
	public static final RegistryObject<Item> GREAT_RUNESTONE = REGISTRY.register("great_runestone", () -> new GreatRunestoneItem());
	public static final RegistryObject<Item> POWERFUL_RUNESTONE = REGISTRY.register("powerful_runestone", () -> new PowerfulRunestoneItem());
	public static final RegistryObject<Item> LEGENDARY_RUNESTONE = REGISTRY.register("legendary_runestone", () -> new LegendaryRunestoneItem());
	public static final RegistryObject<Item> DIVINE_RUNESTONE = REGISTRY.register("divine_runestone", () -> new DivineRunestoneItem());
	public static final RegistryObject<Item> NEST_ICON = REGISTRY.register("nest_icon", () -> new NestIconItem());
	public static final RegistryObject<Item> FARMERS_SUNFLOWER_HEAD = REGISTRY.register("farmers_sunflower_head", () -> new FarmersSunflowerHeadItem());
	public static final RegistryObject<Item> BOOK1_ICON = REGISTRY.register("book1_icon", () -> new BookIconItem());
	public static final RegistryObject<Item> BOOK2_ICON = REGISTRY.register("book2_icon", () -> new Book2IconItem());
	public static final RegistryObject<Item> BOOK3_ICON = REGISTRY.register("book3_icon", () -> new Book3IconItem());
	public static final RegistryObject<Item> SCROLL_ICON = REGISTRY.register("scroll_icon", () -> new ScrollIconItem());
	public static final RegistryObject<Item> LIGHT_BLUE_SCROLL_ICON = REGISTRY.register("light_blue_scroll_icon", () -> new LightBlueScrollIconItem());
	public static final RegistryObject<Item> AGILITY_OF_THE_LYNX = REGISTRY.register("agility_of_the_lynx", () -> new AgilityoftheLynxItem());
	public static final RegistryObject<Item> ANCIENT_WRITINGS = REGISTRY.register("ancient_writings", () -> new AncientWritingsItem());
	public static final RegistryObject<Item> CARTOGRAPHERS_NOTES = REGISTRY.register("cartographers_notes", () -> new CartographersNotesItem());
	public static final RegistryObject<Item> CODEX_OF_TRUTH = REGISTRY.register("codex_of_truth", () -> new CodexOfTruthItem());
	public static final RegistryObject<Item> MYSTERIOUS_MANUSCRIPT = REGISTRY.register("mysterious_manuscript", () -> new MysteriousManuscriptItem());
	public static final RegistryObject<Item> POWER_OF_THE_BUTTERFLY = REGISTRY.register("power_of_the_butterfly", () -> new PowerOfTheButterflyItem());
	public static final RegistryObject<Item> SCROLL_OF_STRENGTH = REGISTRY.register("scroll_of_strength", () -> new ScrollOfStrengthItem());
	public static final RegistryObject<Item> TRAVELERS_DIARY = REGISTRY.register("travelers_diary", () -> new TravelersDiaryItem());
	public static final RegistryObject<Item> BOTTLE_WITH_OIL = REGISTRY.register("bottle_with_oil", () -> new BottleWithOilItem());
	public static final RegistryObject<Item> PEELED_FARMERS_SUNFLOWER_SEED = REGISTRY.register("peeled_farmers_sunflower_seed", () -> new PeeledFarmersSunflowerSeedItem());
	public static final RegistryObject<Item> FRIED_FARMERS_SUNFLOWER_SEED = REGISTRY.register("fried_farmers_sunflower_seed", () -> new FriedFarmersSunflowerSeedItem());
	public static final RegistryObject<Item> CRANK = REGISTRY.register(VortexModBlocks.CRANK.getId().getPath(), () -> new CrankDisplayItem(VortexModBlocks.CRANK.get(), new Item.Properties()));
	public static final RegistryObject<Item> OIL_ROLL = block(VortexModBlocks.OIL_ROLL);
	public static final RegistryObject<Item> PRESERVES_JAR = block(VortexModBlocks.PRESERVES_JAR);
	public static final RegistryObject<Item> BRINE = REGISTRY.register("brine", () -> new BrineItem());
	public static final RegistryObject<Item> TABLET_OF_CLEAR_SKY = REGISTRY.register("tablet_of_clear_sky", () -> new TabletOfClearSkyItem());
	public static final RegistryObject<Item> TABLET_OF_BREATH_OF_WIND = REGISTRY.register("tablet_of_breath_of_wind", () -> new TabletOfBreathOfWindItem());
	public static final RegistryObject<Item> TABLET_OF_SWINGING_MAPLE = REGISTRY.register("tablet_of_swinging_maple", () -> new TabletOfSwingingMapleItem());
	public static final RegistryObject<Item> TABLET_OF_FAR_THUNDER = REGISTRY.register("tablet_of_far_thunder", () -> new TabletOfFarThunderItem());
	public static final RegistryObject<Item> TABLET_OF_CATACLYSM = REGISTRY.register("tablet_of_cataclysm", () -> new TabletOfCataclysmItem());
	public static final RegistryObject<Item> TABLET_OF_TREMBLING_OF_EARTH = REGISTRY.register("tablet_of_trembling_of_earth", () -> new TabletOfTremblingOfEarthItem());
	public static final RegistryObject<Item> TABLET_OF_LOST_HOUSES = REGISTRY.register("tablet_of_lost_houses", () -> new TabletOfLostHousesItem());
	public static final RegistryObject<Item> TABLET_OF_FALLEN_DESTINIES = REGISTRY.register("tablet_of_fallen_destinies", () -> new TabletOfFallenDestiniesItem());
	public static final RegistryObject<Item> TABLET_OF_ABANDONED_PLACES = REGISTRY.register("tablet_of_abandoned_places", () -> new TabletOfAbandonedPlacesItem());
	public static final RegistryObject<Item> TABLET_OF_STORM = REGISTRY.register("tablet_of_storm", () -> new TabletOfStormItem());
	public static final RegistryObject<Item> ENCHANTERS_CONTRACT = REGISTRY.register("enchanters_contract", () -> new EnchantersContractItem());
	public static final RegistryObject<Item> WARRIORS_CONTRACT = REGISTRY.register("warriors_contract", () -> new WarriorsContractItem());
	public static final RegistryObject<Item> FARMERS_CONTRACT = REGISTRY.register("farmers_contract", () -> new FarmersContractItem());
	public static final RegistryObject<Item> INNOVATORS_CONTRACT = REGISTRY.register("innovators_contract", () -> new InnovatorsContractItem());
	public static final RegistryObject<Item> TRAVELERS_CONTRACT = REGISTRY.register("travelers_contract", () -> new TravelersContractItem());
	public static final RegistryObject<Item> DWARVEN_GEAR = REGISTRY.register("dwarven_gear", () -> new DwarvenGearItem());
	public static final RegistryObject<Item> ESSENCE_OF_MELTING = REGISTRY.register("essence_of_melting", () -> new EssenceOfMeltingItem());
	public static final RegistryObject<Item> ESSENCE_OF_NATURE = REGISTRY.register("essence_of_nature", () -> new EssenceOfNatureItem());
	public static final RegistryObject<Item> ESSENCE_OF_MAGIC = REGISTRY.register("essence_of_magic", () -> new EssenceOfMagicItem());
	public static final RegistryObject<Item> WATER_WELL = block(VortexModBlocks.WATER_WELL);
	public static final RegistryObject<Item> MAYO = REGISTRY.register("mayo", () -> new MayoItem());
	public static final RegistryObject<Item> DEFAMED_CRYSTAL_OUTGROWTH_HELMET = REGISTRY.register("defamed_crystal_outgrowth_helmet", () -> new DefamedCrystalOutgrowthItem.Helmet());
	public static final RegistryObject<Item> THE_CURSED_HAND = REGISTRY.register("the_cursed_hand", () -> new TheCursedHandItem());
	public static final RegistryObject<Item> MYSTICAL_WELL = block(VortexModBlocks.MYSTICAL_WELL);
	public static final RegistryObject<Item> MYSTICAL_COIN = REGISTRY.register("mystical_coin", () -> new MysticalCoinItem());
	public static final RegistryObject<Item> ROUGH_STONY_MIX = REGISTRY.register("rough_stony_mix", () -> new RoughStonyMixItem());
	public static final RegistryObject<Item> ORCISH_SKULL = REGISTRY.register("orcish_skull", () -> new OrcishSkullItem());
	public static final RegistryObject<Item> ORCISH_QUIVER = REGISTRY.register("orcish_quiver", () -> new OrcishQuiverItem());
	public static final RegistryObject<Item> ORCISH_MONOCLE = REGISTRY.register("orcish_monocle", () -> new OrcishMonocleItem());
	public static final RegistryObject<Item> ORCISH_BOTTLE = REGISTRY.register("orcish_bottle", () -> new OrcishBottleItem());
	public static final RegistryObject<Item> ORCISH_ARTIFACT = REGISTRY.register("orcish_artifact", () -> new OrcishArtifactItem());
	public static final RegistryObject<Item> HEXAGONAL_MANA_STONE = REGISTRY.register("hexagonal_mana_stone", () -> new HexagonalManaStoneItem());
	public static final RegistryObject<Item> THE_PEARL_OF_GNUMUSES = REGISTRY.register("the_pearl_of_gnumuses", () -> new ThePearlOfGnumusesItem());
	public static final RegistryObject<Item> THE_PLAGUE_INGOT = REGISTRY.register("the_plague_ingot", () -> new ThePlagueIngotItem());
	public static final RegistryObject<Item> ORCISH_DUST = REGISTRY.register("orcish_dust", () -> new OrcishDustItem());
	public static final RegistryObject<Item> OZGLOZ_INGOT = REGISTRY.register("ozgloz_ingot", () -> new OzglozIngotItem());
	public static final RegistryObject<Item> BLOOMING_STEEL_INGOT = REGISTRY.register("blooming_steel_ingot", () -> new BloomingSteelIngotItem());
	public static final RegistryObject<Item> INGOT_OF_SPROUTED_STEEL = REGISTRY.register("ingot_of_sprouted_steel", () -> new IngotOfSproutedSteelItem());
	public static final RegistryObject<Item> ESSENCE_OF_THE_STORM = REGISTRY.register("essence_of_the_storm", () -> new EssenceOfTheStormItem());
	public static final RegistryObject<Item> RAW_RAT_TOKEN = REGISTRY.register("raw_rat_token", () -> new RawRatTokenItem());
	public static final RegistryObject<Item> THE_ESSENCE_OF_A_DEMI_GOD = REGISTRY.register("the_essence_of_a_demi_god", () -> new TheEssenceOfADemiGodItem());
	public static final RegistryObject<Item> OZGLOZ_MIXTURE = REGISTRY.register("ozgloz_mixture", () -> new OzglozMixtureItem());
	public static final RegistryObject<Item> THE_BEACON_OF_DESTINY = block(VortexModBlocks.THE_BEACON_OF_DESTINY);
	public static final RegistryObject<Item> ESSENCE_OF_EARTHQUAKE = REGISTRY.register("essence_of_earthquake", () -> new EssenceOfEarthquakeItem());
	public static final RegistryObject<Item> GHOSTLY_SHARD = REGISTRY.register("ghostly_shard", () -> new GhostlyShardItem());
	public static final RegistryObject<Item> WILL_OF_THE_CHAOSBORN = REGISTRY.register("will_of_the_chaosborn", () -> new WillOfTheChaosbornItem());
	public static final RegistryObject<Item> TEAR_OF_THE_ALLFATHERS = REGISTRY.register("tear_of_the_allfathers", () -> new TearOfTheAllfathersItem());
	public static final RegistryObject<Item> ATOMIC_SUSPENSION = REGISTRY.register("atomic_suspension", () -> new AtomicSuspensionItem());
	public static final RegistryObject<Item> ESSENCE_OF_CATACLYSM = REGISTRY.register("essence_of_cataclysm", () -> new EssenceOfCataclysmItem());
	public static final RegistryObject<Item> DYING_BREATH_OF_FORGOTTEN_TIMES = REGISTRY.register("dying_breath_of_forgotten_times", () -> new DyingBreathOfForgottenTimesItem());
	public static final RegistryObject<Item> HEAT_OF_THE_SCORCHING_DESERT = REGISTRY.register("heat_of_the_scorching_desert", () -> new HeatOfTheScorchingDesertItem());
	public static final RegistryObject<Item> HUM_OF_UNDERWATER_DEPTHS = REGISTRY.register("hum_of_underwater_depths", () -> new HumOfUnderwaterDepthsItem());
	public static final RegistryObject<Item> WHISPER_OF_THE_ALLURING_ABYSS = REGISTRY.register("whisper_of_the_alluring_abyss", () -> new WhisperOfTheAlluringAbyssItem());
	public static final RegistryObject<Item> CLANK_OF_TEMPERED_METALS = REGISTRY.register("clank_of_tempered_metals", () -> new ClankOfTemperedMetalsItem());
	public static final RegistryObject<Item> HOWL_OF_MERCILESS_FLAME = REGISTRY.register("howl_of_merciless_flame", () -> new HowlOfMercilessFlameItem());
	public static final RegistryObject<Item> CLAMOR_OF_DEATHS_EMISSARIES = REGISTRY.register("clamor_of_deaths_emissaries", () -> new ClamorOfDeathsEmissariesItem());
	public static final RegistryObject<Item> CACKLE_OF_VEXING_BLIGHT = REGISTRY.register("cackle_of_vexing_blight", () -> new CackleOfVexingBlightItem());
	public static final RegistryObject<Item> RIFT_OF_FORGOTTEN_CHAOS = REGISTRY.register("rift_of_forgotten_chaos", () -> new RiftOfForgottenChaosItem());
	public static final RegistryObject<Item> VISAGE_OF_DEPARTED_RULERS = REGISTRY.register("visage_of_departed_rulers", () -> new VisageOfDepartedRulersItem());
	public static final RegistryObject<Item> RAW_CHARGED_QUALADIUM = REGISTRY.register("raw_charged_qualadium", () -> new RawChargedQualadiumItem());
	public static final RegistryObject<Item> RAW_GEMINIUM = REGISTRY.register("raw_geminium", () -> new RawGeminiumItem());
	public static final RegistryObject<Item> MATERIAL_ESSENCE = REGISTRY.register("material_essence", () -> new MaterialEssenceItem());
	public static final RegistryObject<Item> CORE_OF_MATTER = REGISTRY.register("core_of_matter", () -> new CoreOfMatterItem());
	public static final RegistryObject<Item> WHIRL_OF_EXISTENCE = REGISTRY.register("whirl_of_existence", () -> new WhirlOfExistenceItem());
	public static final RegistryObject<Item> RESONATING_CRYSTAL_HEART = REGISTRY.register("resonating_crystal_heart", () -> new ResonatingCrystalHeartItem());
	public static final RegistryObject<Item> ULTIMATE_RUNESTONE = REGISTRY.register("ultimate_runestone", () -> new UltimateRunestoneItem());
	public static final RegistryObject<Item> INSANE_RUNESTONE = REGISTRY.register("insane_runestone", () -> new InsaneRunestoneItem());
	public static final RegistryObject<Item> BANDIT_HEAD = block(VortexModBlocks.BANDIT_HEAD);
	public static final RegistryObject<Item> ELDER_HEAD = block(VortexModBlocks.ELDER_HEAD);
	public static final RegistryObject<Item> ENCHANTRESS_HEAD = block(VortexModBlocks.ENCHANTRESS_HEAD);
	public static final RegistryObject<Item> ENGINEER_HEAD = block(VortexModBlocks.ENGINEER_HEAD);
	public static final RegistryObject<Item> LIGHT_HEAD = block(VortexModBlocks.LIGHT_HEAD);
	public static final RegistryObject<Item> PROTAGONIST_HEAD = block(VortexModBlocks.PROTAGONIST_HEAD);

	// Start of user code block custom items
	// End of user code block custom items
	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}
}
