modLoader="javafml"
loaderVersion="[47,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="vortex"
version="0.0.22"
displayName="Vortex"
displayURL="https://discord.gg/sJayn3BYDh"
credits="Hrumer, Samuelchik, Linnett"
authors="Saudade Studio (HorizonExpand)"
description="\u00A7oNothing \u00A7k\u0412\u044B \u044D\u0442\u043E\u0433\u043E \u043D\u0435 \u0443\u0432\u0438\u0434\u0438\u0442\u0435"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.vortex]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.vortex]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration